export type {
  SmcDetectionKind,
  SmcDetectorConfig,
  SmcSwingConfig,
  SmcStructureConfig,
  SmcBosConfig,
  SmcChochConfig,
  SmcDisplacementConfig,
  SmcFvgConfig,
  SmcEqualLevelsConfig,
  SmcLiquiditySweepConfig,
  SmcOrderBlockConfig,
  SmcSwingEvent,
  SmcClassifiedSwingEvent,
  SmcBosEvent,
  SmcChochEvent,
  SmcDisplacementEvent,
  SmcFvgEvent,
  SmcEqualLevelEvent,
  SmcLiquiditySweepEvent,
  SmcOrderBlockEvent,
  SmcDetectionDiagnostics,
  SmcDetectionResult,
  SmcEvent,
  SmcEventRef,
  SmcStructureState,
  SmcSwingClassification,
  SmcInvariantCounts,
  SmcModuleTiming,
} from './types'
export { SMC_DETECTOR_VERSION } from './types'

export {
  DEFAULT_SMC_DETECTOR_CONFIG,
  PHASE1_COMPAT_SMC_CONFIG,
  cloneSmcDetectorConfig,
} from './defaults'

export {
  validateSmcDetectorConfig,
  SMC_CONFIG_BOUNDS,
  moduleDependencyReason,
  type SmcConfigValidationResult,
} from './validation'

export { detectConfirmedSwings } from './swing-detector'
export { detectBreakOfStructure } from './bos-detector'
export {
  classifyInternalExternalStructure,
  swingProminence,
} from './structure-classifier'
export {
  buildCanonicalLiquidityLevels,
} from './liquidity-sweep-detector'
export {
  countStructureBreaks,
  countReviewableEvents,
  buildDiagnosticsSummary,
  buildEventCountBreakdownFields,
} from './diagnostics-summary'
export { detectStructureBreaks } from './structure-breaks'
export { detectDisplacement, isDisplacementCandleAt } from './displacement-detector'
export { detectFairValueGaps } from './fvg-detector'
export { detectEqualLevels } from './equal-levels-detector'
export { detectLiquiditySweeps } from './liquidity-sweep-detector'
export { detectOrderBlocks } from './order-block-detector'
export {
  detectSmc,
  detectSmcUntil,
  resolveSmcConfig,
  emptySmcDetectionResult,
  eventsAtCandle,
} from './detection-pipeline'
export {
  auditSmcInvariants,
  sanitizeSmcDetectionResult,
  isValidBullishBos,
  isValidBearishBos,
  type SmcInvariantReport,
} from './invariants'

export {
  SMC_MODULES,
  SMC_DETECTION_MODULE_ORDER,
  listActiveSmcModules,
  listPlannedSmcModules,
  type SmcModuleDescriptor,
  type SmcModuleStatus,
  type SmcModuleConfigKey,
} from './modules'

export {
  SMC_RANKING_VERSION,
  SMC_VISIBILITY_POLICIES,
  scoreSmcEvent,
  eventFamilyKey,
  rankSmcDetectionResult,
  applySmcIntelligence,
  withSmcVisibilityMode,
  getEventImportance,
  isEventVisibleByRanking,
  filterDetectionByRanking,
  relatedEventsByRank,
  buildVisibilityPipelineDiagnostics,
  withRenderedCounts,
  visibilityModuleForKind,
  type SmcVisibilityMode,
  type SmcImportanceReason,
  type SmcRankedEventMeta,
  type SmcRankingDiagnostics,
  type SmcIntelligenceLayer,
  type SmcVisibilityPolicy,
  type SmcVisibilityStageCounts,
  type SmcVisibilityModuleBucket,
  type SmcVisibilityPipelineDiagnostics,
} from './ranking'

export {
  DEFAULT_SMC_MATCH_TOLERANCE,
  SMC_ACCEPTANCE_GATES,
  validationModuleForKind,
  scoreEventMatch,
  matchGoldenLabels,
  precisionRecall,
  reviewedAgreement,
  acceptanceStatusForModule,
  buildModuleMetrics,
  SMC_VALIDATION_MODULES,
  toDetectedProbes,
  filterProbesByModule,
  qmlPatternToProbe,
  matchQmlGoldenLabels,
  DEFAULT_QML_MATCH_TOLERANCE,
  validateProgressiveConsistency,
  earliestAppearanceIndex,
  eventsEqualByIdentity,
  evaluateSmcValidation,
  goldenLabelFromProbe,
  createGoldenDatasetId,
  type SmcValidationModule,
  type SmcModuleAcceptanceStatus,
  type SmcGoldenLabel,
  type SmcGoldenDatasetScope,
  type SmcGoldenDataset,
  type SmcEventMatchTolerance,
  type SmcDetectedEventProbe,
  type SmcEventMatch,
  type SmcModuleValidationMetrics,
  type SmcLookAheadViolation,
  type SmcProgressiveConsistencyReport,
  type SmcWrongTagCount,
  type SmcValidationReport,
  type SmcAcceptanceGate,
  type SmcReviewSample,
  type EvaluateValidationInput,
  type QmlMatchTolerance,
  type QmlGoldenLabel,
} from './validation-suite'

export {
  DEFAULT_ZONE_LIFECYCLE_SETTINGS,
  emptyLifecycleInvariantCounts,
  projectFvgZones,
  projectOrderBlockZones,
  projectLiquidityZones,
  filterZonesBySmartVisibility,
  projectStructureRelevance,
  auditLifecycleProjectionInvariants,
  projectSmcLifecycle,
  createMockSetupVisualContext,
  ZONE_LIFECYCLE_VERSION,
  DEFAULT_EXPIRE_AFTER_CANDLES,
  transitionZoneLifecycle,
  isLiveLifecycleState,
  isTerminalLifecycleState,
  runZoneLifecycleEngine,
  filterZonesByLifecycleVisibility,
  renderStyleForLifecycleState,
  renderStyleForZone,
  toChartZoneState,
  fromChartZoneState,
  lifecycleStateLabel,
  buildZoneLifecycleReport,
  managedZoneToProjection,
  type SmcChartZoneState,
  type SmcZoneKind,
  type SmcStructureRelevance,
  type SmcSmartVisibilityPreset,
  type SmcZoneProjection,
  type SmcStructureEventProjection,
  type SmcSetupVisualContext,
  type SmcZoneLifecycleSettings,
  type SmcLifecycleDiagnostics,
  type SmcLifecycleInvariantCounts,
  type SmcLifecycleProjectionResult,
  type ProjectSmcLifecycleInput,
  type ZoneLifecycleState,
  type ZoneLifecycleType,
  type ZoneLifecycleDirection,
  type ZoneLifecycleFamily,
  type ZoneLifecycleMeta,
  type ZoneLifecycleTransitionInput,
  type ZoneLifecycleTransitionResult,
  type ZoneLifecycleEngineInput,
  type ZoneLifecycleEngineResult,
  type ZoneLifecycleRenderStyle,
  type ZoneLifecycleVisibilityMode,
  type ZoneLifecycleReport,
} from './lifecycle'

export {
  SMC_DOW_THEORY_VERSION,
  analyzeDowTheory,
  applyDowTheoryLayer,
  emptyDowTheoryLayer,
  toDowTheorySnapshot,
  classifyDowSwingProgression,
  inferDowTrend,
  type DowSwingLabel,
  type DowTrend,
  type DowStructurePhase,
  type SmcDowSwingMeta,
  type SmcDowTheorySnapshot,
  type SmcDowTheoryDiagnostics,
  type SmcDowTheoryLayer,
  type DowTheoryClassifiedSwing,
} from './dow-theory'

export {
  SMC_QML_VERSION,
  DEFAULT_QML_CONFIG,
  cloneQmlConfig,
  resolveQmlConfig,
  detectQmlPatterns,
  emptyQmlLayer,
  selectQmlSource,
  advanceQmlLifecycle,
  projectQmlZones,
  scoreQmlPattern,
  buildQmlDiagnostics,
  auditQmlInvariants,
  emptyQmlInvariantCounts,
  compareQmlProgressiveFull,
  type QmlConfig,
  type QmlDirection,
  type QmlStatus,
  type QmlZoneMode,
  type QmlRetestMode,
  type QmlConfirmationMode,
  type QmlInvalidationMode,
  type QmlStructureScope,
  type QmlCheck,
  type QmlPattern,
  type QmlDiagnostics,
  type QmlInvariantCounts,
  type SmcQmlLayer,
  type DetectQmlInput,
} from './qml'

export {
  BUILTIN_SMC_PROFILES,
  BUILTIN_SMC_PRESETS,
  QUANTLAB_DEFAULT_PROFILE,
  ICT_INSPIRED_PROFILE,
  SWING_STRUCTURE_PROFILE,
  INTERNAL_EXTERNAL_PROFILE,
  CUSTOM_PROFILE_TEMPLATE,
  getBuiltinSmcProfile,
  listBuiltinSmcProfiles,
  listBuiltinSmcPresets,
  countProfileEvents,
  describeCandleEventDifference,
  type SmcDetectionProfile,
  type SmcProfileId,
  type SmcConfigPreset,
  type SmcProfileCompareCounts,
} from './profiles'
